# Generated by Django 4.2.4 on 2023-08-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.FloatField(max_length=10)),
                ('Weight', models.FloatField(max_length=10)),
                ('bmi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_title', models.CharField(max_length=100)),
                ('Recipe_desc', models.CharField(max_length=5000)),
                ('Recipe_img', models.ImageField(default='No Image selected', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=100)),
                ('user_lname', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=5000)),
                ('user_pwd', models.CharField(max_length=5000)),
            ],
        ),
    ]
