# Generated by Django 4.2.4 on 2023-08-27 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Recipe_ing',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
