# Generated by Django 4.2.4 on 2023-08-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0002_recipe_recipe_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='Height',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='Weight',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=123),
        ),
    ]
