# Generated by Django 4.2.3 on 2023-09-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0003_alter_bmi_height_alter_bmi_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
