# Generated by Django 4.2.3 on 2023-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0004_bmi_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_title', models.CharField(max_length=100)),
                ('Plan_desc', models.CharField(max_length=5000)),
            ],
        ),
    ]
