# Generated by Django 4.2.3 on 2023-09-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0005_workoutplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutPlan',
            new_name='Workout',
        ),
    ]
