# Generated by Django 4.2.3 on 2023-09-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0006_rename_workoutplan_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecPlan_title', models.CharField(max_length=100)),
                ('RecPlan_desc', models.CharField(max_length=5000)),
            ],
        ),
    ]
