# Generated by Django 4.2.4 on 2023-09-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0008_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='user_id',
        ),
    ]
