# Generated by Django 4.2.4 on 2023-09-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0010_rename_user_id_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FijiFit.user'),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='Height',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='Weight',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FijiFit.user'),
        ),
    ]
