# Generated by Django 4.2.3 on 2023-09-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0011_bmi_user_alter_bmi_height_alter_bmi_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='Height',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='Weight',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='bmi',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FijiFit.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pwd',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
