# Generated by Django 4.2.3 on 2023-09-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0013_alter_bmi_user_alter_submission_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
    ]
