# Generated by Django 4.2.3 on 2023-10-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0017_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
