# Generated by Django 4.2.3 on 2023-10-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0021_remove_exercise_workout_exercise_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
    ]
