# Generated by Django 4.2.3 on 2023-10-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0022_remove_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FijiFit.workout'),
        ),
    ]
