# Generated by Django 4.2.3 on 2023-10-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0023_exercise_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
    ]
