# Generated by Django 4.2.3 on 2023-10-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0024_remove_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='Plan_desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Plan_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
