# Generated by Django 4.2.3 on 2023-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0025_alter_workout_plan_desc_alter_workout_plan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recworkout',
            name='RecPlan_img',
            field=models.ImageField(default='No Image selected', upload_to='media/'),
        ),
    ]
