# Generated by Django 4.2.3 on 2023-10-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0026_recworkout_recplan_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recworkout',
            name='user',
        ),
        migrations.CreateModel(
            name='RecExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecEx_title', models.CharField(max_length=100)),
                ('workoutRec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FijiFit.recworkout')),
            ],
        ),
    ]
