# Generated by Django 4.2.3 on 2023-10-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0028_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recworkout',
            name='categoryWrk',
            field=models.CharField(blank=True, choices=[('underweight', 'Underweight'), ('normal', 'Normal'), ('overweight', 'Overweight'), ('obese', 'Obese')], max_length=20, null=True),
        ),
    ]
