# Generated by Django 4.2.3 on 2023-10-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0030_exercise_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_reps_Text', models.CharField(max_length=100)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='FijiFit.exercise')),
            ],
        ),
    ]
