# Generated by Django 4.2.3 on 2023-10-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0031_bmi_timestamp_sets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sets',
        ),
    ]
