# Generated by Django 4.2.3 on 2023-10-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0034_workout_plan_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Plan_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='Plan_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
