# Generated by Django 4.2.3 on 2023-10-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0036_workout_plan_incomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Plan_setDate',
            field=models.DateField(null=True),
        ),
    ]
