# Generated by Django 4.2.3 on 2023-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0038_workout_plan_settime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='Plan_setTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Plan_timestamp',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
