# Generated by Django 4.2.3 on 2023-10-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0039_alter_workout_plan_settime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='Plan_date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='Plan_timestamp',
        ),
    ]
