# Generated by Django 4.2.3 on 2023-10-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0042_remove_workout_plan_settime_alter_bmi_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='Plan_setDate',
            new_name='Plan_setDateTime',
        ),
    ]
