# Generated by Django 4.2.4 on 2023-10-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FijiFit', '0043_rename_plan_setdate_workout_plan_setdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recexercise',
            name='RecEx_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
